
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      # Persist the SQLite database on the host machine
      - ./server/actions_monitor.db:/app/actions_monitor.db
    environment:
      # Tell the app where to find the database inside the container
      - DB_PATH=/app/actions_monitor.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
